# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Update Hosts

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REPO_URL: https://github.com/cr4r/host-to-adguard
  TZ: Asia/Jakarta

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: |
      npm ci
      npm run build --if-present
      npm i
      node index.js
      echo "PACKAGED_OUTPUTPATH=${PWD}/hosts" >> $GITHUB_ENV
      echo "PACKAGED_OUTPUTDATE=$(date +"%Y.%m.%d.%H%M")" >> $GITHUB_ENV
    - name: Upload hasil convert
      uses: cr4r/release-action@v1
      with:
        tag: Hosts-${{ env.PACKAGED_OUTPUTDATE }}
        artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*
        allowUpdates: true
        token: ${{ secrets.GITHUB_TOKEN }}
        body: |
          Convert Host untuk Adguard Filter
          Host Meliputi:
            - Steven Black
            - Adguard CNAME Tracker
            - Adaway
            - Minecraft Tracker
          
          
          
          
          
